### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by subnut** [Sameerkash/Focus#1]
Can you please provide a pre-built APK for a non-app-developer?
Please :innocent: ?

<br>

P.S. How/Where did you generate that profile picture of yours? I really like it...

**Comment by sameeerkashyap** [comment]
Hey @subnut!, Thanks for your interest but this app is as good as dummy as I've barely worked on it and never got the time to explore the options since flutter doesn't have really good platform-specific support, this project is a bit hard to make it customizable and the vision I have in my mind. But I'm learning native development now and hopefully, I'll make this a good product one day and it'll definitely be on the play store if I'm able to make it complete it. So fingers crossed, and I'll definitely notify you through this same thread once it's up and usable.

Thanks again for your interest.

And it isn't generated, I made it using photoshop, you'll find a ton of tutorials on youtube. It's easy.
